"use client";

import React, { useState } from 'react';
import { ShieldCheck, AlertTriangle, UploadCloud, ChevronRight, Loader2, CheckCircle2, XCircle, FileText, BookOpen, Download, Mail, Zap } from 'lucide-react';

export default function LandingPage() {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<any>(null);
  const [truthSource, setTruthSource] = useState("");
  const [email, setEmail] = useState("");

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setLoading(true);
    const formData = new FormData();
    formData.append('file', file);
    formData.append('truthSource', truthSource);

    try {
      const response = await fetch('/api/audit', { method: 'POST', body: formData });
      const data = await response.json();
      setResults(data);
    } catch (error) {
      alert("Analysis failed.");
    } finally { setLoading(false); }
  };

  const getRiskColor = (level?: string) => {
    if (level === 'HIGH') return 'text-red-500 border-red-500/20 bg-red-500/10';
    if (level === 'MEDIUM') return 'text-amber-500 border-amber-500/20 bg-amber-500/10';
    return 'text-emerald-500 border-emerald-500/20 bg-emerald-500/10';
  };

  return (
    <div className="min-h-screen bg-[#050505] text-slate-300 font-sans selection:bg-emerald-500/30 selection:text-emerald-400">
      {/* Navigation */}
      <nav className="max-w-6xl mx-auto py-8 px-6 flex justify-between items-center">
        <div className="text-2xl font-black tracking-tighter flex items-center gap-2 text-white italic">
          <Zap className="text-emerald-500 fill-emerald-500" size={24} /> TRUTHIFIER
        </div>
        <div className="hidden md:flex gap-8 text-xs font-bold uppercase tracking-widest text-slate-500">
          <a href="#mission" className="hover:text-emerald-500 transition">Mission</a>
          <a href="#audit" className="hover:text-emerald-500 transition">Terminal</a>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto pt-12 pb-32 px-6">
        {/* Mission & Problem Section */}
        <section id="mission" className="mb-24 text-center">
          <div className="inline-block px-3 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/5 text-emerald-500 text-[10px] font-bold uppercase tracking-[0.2em] mb-6">
            Cyber-Security for LLMs
          </div>
          <h1 className="text-6xl md:text-7xl font-black text-white mb-8 tracking-tighter">
            AI Truth <span className="text-emerald-500">Protocol.</span>
          </h1>
          <p className="text-slate-500 text-xl max-w-2xl mx-auto leading-relaxed mb-12">
            The Problem: <span className="text-slate-300">Generative AI is inherently creative, not factual.</span> This "creativity" leads to hallucinations that violate company policy and create legal liability.
          </p>
          <div className="grid md:grid-cols-2 gap-6 text-left max-w-4xl mx-auto">
            <div className="p-8 rounded-2xl bg-[#0A0A0A] border border-white/5">
              <h3 className="text-white font-bold mb-3 flex items-center gap-2">
                <ShieldCheck className="text-emerald-500" size={18} /> Our Solution
              </h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                Truthifier provides a forensic layer for LLM outputs. We cross-reference every claim against your private "Truth Source" documentation to stop hallucinations before they reach the customer.
              </p>
            </div>
            <div className="p-8 rounded-2xl bg-[#0A0A0A] border border-white/5">
              <h3 className="text-white font-bold mb-3 flex items-center gap-2 italic">
                <Zap className="text-emerald-500" size={18} /> The Mission
              </h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                To build the global standard for AI Factual Integrity, ensuring that every word generated by an enterprise model is grounded in institutional truth.
              </p>
            </div>
          </div>
        </section>

        {/* The Audit Terminal */}
        <section id="audit" className="max-w-3xl mx-auto">
          <div className="bg-[#0A0A0A] border border-white/5 rounded-3xl p-1 shadow-2xl shadow-emerald-500/5">
            <div className="p-8 md:p-12">
              {!results ? (
                <div className="space-y-8">
                  <div>
                    <label className="text-[10px] font-bold uppercase tracking-widest text-emerald-500 mb-4 block">01 // TRUTH SOURCE DOCUMENTATION</label>
                    <textarea 
                      className="w-full bg-black border border-white/10 rounded-xl p-5 text-sm text-emerald-500 font-mono focus:border-emerald-500/50 outline-none h-40 transition-all placeholder:text-emerald-900/50"
                      placeholder="Paste policy documentation here..."
                      value={truthSource}
                      onChange={(e) => setTruthSource(e.target.value)}
                    />
                  </div>

                  <div>
                    <label className="text-[10px] font-bold uppercase tracking-widest text-emerald-500 mb-4 block">02 // UPLOAD INTERFACE</label>
                    <div className="bg-black border border-white/10 border-dashed rounded-2xl p-16 text-center hover:border-emerald-500/40 transition cursor-pointer group">
                      <input type="file" className="hidden" id="log-upload" onChange={handleUpload} accept=".json" />
                      <label htmlFor="log-upload" className="cursor-pointer">
                        {loading ? <Loader2 className="animate-spin mx-auto text-emerald-500" size={40} /> : (
                          <>
                            <UploadCloud className="mx-auto mb-6 text-emerald-900 group-hover:text-emerald-500 transition-colors" size={48} strokeWidth={1.5} />
                            <div className="bg-emerald-600 hover:bg-emerald-500 text-black px-12 py-4 rounded-full font-black text-sm uppercase tracking-tighter inline-flex items-center gap-2 transition transform group-hover:scale-105">
                              Run Truth Audit <ChevronRight size={18} />
                            </div>
                          </>
                        )}
                      </label>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-700">
                  <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 border-b border-white/5 pb-8">
                    <div>
                      <h2 className="text-4xl font-black text-white italic">INTEGRITY: {results.score}%</h2>
                      <p className="text-emerald-500 font-mono text-[10px] uppercase tracking-widest mt-2">Analysis Complete // {results.issues} Violations Detected</p>
                    </div>
                    <button onClick={() => setResults(null)} className="text-[10px] font-bold uppercase text-slate-600 hover:text-white transition mt-4 md:mt-0 underline underline-offset-4 tracking-widest">Clear Terminal</button>
                  </div>

                  <div className="space-y-4 mb-12">
                    {results.detailedResults?.map((res: any, i: number) => (
                      <div key={i} className="flex flex-col md:flex-row md:items-center justify-between p-6 bg-black border border-white/5 rounded-xl hover:border-white/10 transition">
                        <div className="flex items-start gap-4 mb-4 md:mb-0">
                          {res.status === 'FLAGGED' ? <AlertTriangle size={20} className="text-emerald-500 shrink-0 mt-1" /> : <CheckCircle2 size={20} className="text-emerald-900 shrink-0 mt-1" />}
                          <span className="text-sm font-medium leading-relaxed">{res.reason}</span>
                        </div>
                        <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest border ${getRiskColor(res.riskLevel)}`}>
                          {res.riskLevel || res.status}
                        </span>
                      </div>
                    ))}
                  </div>

                  {/* Lead Capture form for risky audits */}
                  {results.score < 100 && (
                    <div className="p-8 rounded-3xl bg-emerald-500/5 border border-emerald-500/20">
                      <h4 className="text-white font-bold mb-2 flex items-center gap-2 italic underline underline-offset-4">
                        <Mail size={16} /> SECURE AUDIT REPORT
                      </h4>
                      <p className="text-xs text-slate-500 mb-6">Your AI score indicates factual drift. Enter your corporate email to receive a detailed compliance mitigation roadmap.</p>
                      <div className="flex gap-2">
                        <input 
                          type="email" 
                          placeholder="name@company.com" 
                          className="bg-black border border-emerald-500/20 rounded-xl px-4 py-3 text-sm flex-1 focus:border-emerald-500 outline-none text-emerald-500"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                        />
                        <button className="bg-emerald-600 hover:bg-emerald-500 text-black px-6 py-3 rounded-xl font-bold text-xs uppercase transition tracking-tighter">
                          Get Roadmap
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}